### ISSUE TITLE
how to determine the number of list paragraph？

### ISSUE THREAD

**Issue by Ali1213** [lalalic/docx4js#11]
l'm working to parse the docx file to text, but i can not determine the numbering of list paragraph just by  numId(abstractNumId) and ilvl value. Although it works, sometimes it is wrong. could you give me   some advise？
Look forward to your reply!

**Comment by jmealo** [comment]
@Ali1213: I haven't hit this issue yet, but, since it's transient, I'm wondering if when the user is typing if they split up the list and then joined it again. Is it possible that this created two bulleted lists one starting at 1. and one starting at whatever number it was at when it split? It might be hard to reproduce, but, I know some word processors in the early 2000's did just this (it was observable by editing the document).

**Comment by lalalic** [comment]
Numbering is actually complicated in word. if you find issue in your document, let me know.
