### ISSUE TITLE
API doc not aligned with package

### ISSUE THREAD

**Issue by crystalfp** [lalalic/docx4js#47]
Installed docx4js v. 3.2.9. First try following the documentation:
```
const docx4js = require("docx4js")
docx4js .load("a.docx")
Uncaught TypeError: docx4js.load is not a function
```
I had to insert a new level to use the package:
```
docx4js.docx.load("a.docx")
Promise { <pending> }
```
Could the documentation be updated?
Thanks!
mario

**Comment by okkebal** [comment]
" try following the documentation:" 

Where is this documentation???

**Comment by crystalfp** [comment]
https://github.com/lalalic/docx4js/blob/master/README.md this seems is the only existing documentation.

**Comment by qgustavor** [comment]
Isn't it because the code is written in ES Modules but is distributed [using CommonJS](https://unpkg.com/browse/docx4js@3.2.20/lib/index.js), even if the documentation [implies ES Modules](https://github.com/lalalic/docx4js/blob/73d2234f5328ad4e35d1863cf8d411bd58becdbb/README.md?plain=1#L10)? If you check the distributed code there is no `exports.load`, you either need to use `docx4js.docx.load("~/test.docx")` or `docx4js.default.load("~/test.docx")`.

Couldn't this library be released as ESM instead?
